/**
 * GraphSummary Types
 *
 * TypeScript interfaces mirroring the Python dataclasses from
 * TACO-FOR-ALL/GraphNode_AI/Ky/src/insights/discovery/schema.py
 *
 * These types define the structure for graph analysis insights
 * generated by the GraphSummarizer module.
 */

/**
 * High-level overview of the conversation graph.
 */
export interface OverviewSection {
  /** Total number of conversations in the graph */
  total_conversations: number;

  /** Time range of conversations (e.g., "2024-01-01 ~ 2025-01-01" or "N/A") */
  time_span: string;

  /** Top 3-5 topics/interests identified */
  primary_interests: string[];

  /** Characterization of conversation style (e.g., "기술 심화형", "탐색형") */
  conversation_style: string;

  /** When most conversations occur (or "N/A" if no timestamp data) */
  most_active_period: string;

  /** LLM-generated natural language summary */
  summary_text: string;
}

/**
 * Detailed analysis of a single cluster.
 */
export interface ClusterAnalysis {
  /** Unique cluster identifier (e.g., "cluster_1") */
  cluster_id: string;

  /** Human-readable cluster name */
  name: string;

  /** Number of conversations in this cluster */
  size: number;

  /** Internal edge density (0-1) */
  density: number;

  /** How connected to other clusters (0-1) */
  centrality: number;

  /** Activity status: "active" | "dormant" | "new" | "unknown" */
  recency: "active" | "dormant" | "new" | "unknown";

  /** Top extracted keywords */
  top_keywords: string[];

  /** Key themes identified by LLM */
  key_themes: string[];

  /** Common question types (e.g., ["디버깅", "개념 설명", "비교"]) */
  common_question_types: string[];

  /** LLM-generated insight text */
  insight_text: string;

  /** Node IDs of notable conversations */
  notable_conversations: string[];
}

/**
 * Pattern types that can be identified in the graph.
 */
export type PatternType = "repetition" | "progression" | "gap" | "bridge";

/**
 * Significance levels for patterns.
 */
export type Significance = "high" | "medium" | "low";

/**
 * Identified pattern across the graph.
 */
export interface Pattern {
  /** Type of pattern detected */
  pattern_type: PatternType;

  /** Description of the pattern */
  description: string;

  /** Node IDs or evidence supporting this pattern */
  evidence: string[];

  /** Significance level */
  significance: Significance;
}

/**
 * Connection between two clusters.
 */
export interface ClusterConnection {
  /** Source cluster name */
  source_cluster: string;

  /** Target cluster name */
  target_cluster: string;

  /** Connection strength (0-1) */
  connection_strength: number;

  /** Keywords that bridge the two clusters */
  bridge_keywords: string[];

  /** Description of the connection */
  description: string;
}

/**
 * Recommendation types for actionable items.
 */
export type RecommendationType =
  | "consolidate"
  | "explore"
  | "review"
  | "connect";

/**
 * Priority levels for recommendations.
 */
export type Priority = "high" | "medium" | "low";

/**
 * Actionable recommendation for the user.
 */
export interface Recommendation {
  /** Type of recommendation */
  type: RecommendationType;

  /** Short, actionable title */
  title: string;

  /** 1-2 sentence explanation */
  description: string;

  /** Related node IDs */
  related_nodes: string[];

  /** Priority level */
  priority: Priority;
}

/**
 * Detail levels for summary generation.
 */
export type DetailLevel = "brief" | "standard" | "detailed";

/**
 * Complete graph summary with insights.
 * This is the main response type from the GraphSummarizer.
 */
export interface GraphSummary {
  /** High-level overview */
  overview: OverviewSection;

  /** Cluster analyses */
  clusters: ClusterAnalysis[];

  /** Cross-cutting patterns */
  patterns: Pattern[];

  /** Cluster connections */
  connections: ClusterConnection[];

  /** Actionable recommendations */
  recommendations: Recommendation[];

  /** ISO timestamp when summary was generated */
  generated_at: string;

  /** Level of detail in the summary */
  detail_level: DetailLevel;
}

/**
 * API response wrapper (if needed)
 */
export interface GraphSummaryResponse {
  success: boolean;
  data: GraphSummary | null;
  error?: string;
}
